baseurl = "https://books.estevao.xyz/"
title = "Nelson Estevão"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
googleAnalytics = ""


[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  description = "List of Books"
  copyright = "&copy; 2018 Nelson Estevão."
  sidebarAbout = [
    "I am a Software Engineering Student at University of Minho."
  ]
  # Contact page
  email = "hello@estevao.xyz"

  [params.social]
    facebook      = "nelsonmestevao"
    twitter       = "nelsonmestevao"
    linkedin      = "nelsonmestevao"
    instagram     = ""
    github        = "nelsonmestevao"

  # Nav links in the side bar
  # [[params.navlinks]]
  # name = "About"
  # url = "https://about.estevao.xyz"

  # [[params.navlinks]]
  # name = "Get in touch"
  # url = "contact/"